9 interview card data
SuffolkLITLab/courtformsonline.org pull request #24
Opened 2024-04-29 18:18 UTC by jtmst

This PR addresses issue [19](https://github.com/SuffolkLITLab/courtformsonline.org/issues/19) as well as issue [21](https://github.com/SuffolkLITLab/courtformsonline.org/issues/21)

### Changes:
- Splits TopicsCard into its own component file with updated logic for displaying interviews
- Adds fetchInterviewData file. 
- fetchInterviews logic.  Sorts interviews by topic.
- Simplify page.tsx.  Adds filter and sort logic for topic cards so that only topics with associated interviews are rendered (issue 21)
- Modify topic config data so all always_visible flags are set to false
- Modify server config file for easier addition of jurisdiction data later
- File change count inflated because of yarn cache refresh
- File organization changes, (config files in config dir)

<img width="1174" alt="image" src="https://github.com/SuffolkLITLab/courtformsonline.org/assets/61624970/92c4ba11-9adc-4232-b2ea-fb28b739ec2c">

2024-04-30 20:10 UTC, johnphamvan commented
@nonprofittechy We acknowledge that the .yarn/cache makes these PRs very unwieldy. That's the current yarn best practice right now though. See https://github.com/yarnpkg/berry?tab=readme-ov-file#building-your-own-bundle. We recommend unchecking zip files from the file list.

<img width="363" alt="image" src="https://github.com/SuffolkLITLab/courtformsonline.org/assets/16676676/3501b032-4acc-4fa4-b6d3-9a5a6569b799">

2024-04-30 20:31 UTC, nonprofittechy commented
No worries about the .zip files. I had some trouble running this branch locally but I'll come back with a more specific question.

2024-05-01 18:59 UTC, jtmst commented
> No worries about the .zip files. I had some trouble running this branch locally but I'll come back with a more specific question.

Anything I can help out with getting it to run properly?

2024-05-01 19:40 UTC, nonprofittechy commented
> > No worries about the .zip files. I had some trouble running this branch locally but I'll come back with a more specific question.
> 
> Anything I can help out with getting it to run properly?

So I did both a `yarn install` and then `yarn dev`, as well as `npm install` and `npm run start` but I just get a 404 error.

Maybe I'm having trouble understanding what the new routes are?

2024-05-01 21:38 UTC, jtmst commented
> > > No worries about the .zip files. I had some trouble running this branch locally but I'll come back with a more specific question.
> > 
> > 
> > Anything I can help out with getting it to run properly?
> 
> So I did both a `yarn install` and then `yarn dev`, as well as `npm install` and `npm run start` but I just get a 404 error.
> 
> Maybe I'm having trouble understanding what the new routes are?

Routes should be unchanged and you should still see the homepage on localhost:3000/

2024-05-02 20:20 UTC, nonprofittechy commented
This what I get. Note that I can run other node applications from the same install (and I could run this in the past) so it's not a firewall issue:

![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/adff617a-c1eb-4d31-aef2-5832234b5e02)

2024-05-03 14:52 UTC, nonprofittechy commented on src/app/page.tsx
> +              )
LIST is a hierarchical code. 209A, which is FA-07-00-00-00, should go into the "Family" topic but it's getting sorted into Other

![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/f11bab16-965d-4900-a892-2888fbb8124a)

![image](https://github.com/SuffolkLITLab/courtformsonline.org/assets/7645641/0a8a80a5-e1ef-4563-b333-9c3a0d77214a)

2024-05-03 14:53 UTC, nonprofittechy requested changes
This is looking good **except** we need to parse the LIST topics.

Edit: I suggest a function to see if a topic is contained in or is identical to a top level topic. The current site has some lower-level topics that we promoted to the "top" level, such as Appeals and Domestic Violence. So it's not just enough to strip off all of the numbers.

2024-05-08 20:39 UTC, nonprofittechy approved these changes

2024-05-08 20:52 UTC, merged